# Generated by Django 5.0 on 2025-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio_nacimiento_desde', models.IntegerField()),
                ('anio_nacimiento_hasta', models.IntegerField()),
                ('profesor', models.CharField(max_length=100)),
                ('dias_horarios', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('dni_responsable', models.IntegerField()),
                ('contacto_responsable', models.CharField(max_length=100)),
            ],
        ),
    ]
