# Generated by Django 5.0 on 2025-12-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
            ],
        ),
    ]
